name: Buld and Deploy Code

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    not_BJ:
        runs-on: ubuntu-lastest
        steps:
            - name: Pulling git repo from github
              uses: action/checkout@v3 
            - name: Say Hi to Irteza
              run: echo "Hello Irteza" 


