name: Buld and Deploy Code

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    not_BJ:
        runs-on: ubuntu-latest
        steps:
            - name: Pulling git repo from github
              uses: actions/checkout@v3 
            - name: Say Hi to Irteza
              run: echo "Hello Irteza" 
            - name: Install python v 3.10
              uses: actions/setup-python@v4
              with:
                python-version: '3.10' 
            - name: Upgrade pip
              run: python -m pip install --upgrade pip
            - name: Install all dependencies
              run: pip install -r requirements.txt


